### PR TITLE
add ensureAtLeastOne assertion predicate

### PR DESCRIPTION
**Pull request by giovanepadawan**
It solves [issue#76](https://github.com/jcornaz/kwik/issues/76)

---

This pull request has been developed during [Open Source Saturday #30](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/events/266407734/) meetup in Milan.
[Open Source Saturday](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/)

### CODE REVIEW

**Comment by jcornaz** [comment]
Thank you very much this pull request.

I'll have a look this weekend ;-)

**Comment by jcornaz** [comment]
@giovanepadawan thanks again for your work.

This pull request is of high quality, and I'll definitely use it!

However, it looks like there is a misunderstanding about the goal of the feature. I was obviously not clear enough in the redaction of #76. I am very sorry for that, I'll update the issue description soon, and I'll try to make clearer all my issues marked with "up-for-grab".

In short, I wanted `ensureAtLeastOne` to force the property evaluation (`forAll`) to continue evaluating as many times necessary so that the predicate gets true at least once.

For example if I run: 
```kotlin
var i = 0
forAll(Generator.create { i++ }, iterations = 10) { x ->
  ensureAtLeastOne { x > 100 }
}
```

then the property would not fail, but simply run 100 times.

In case you are wondering: yes it could lead to cases were it'd run forever. It is fine, the build would then fail because when reaching timeout of the test engine or build used. (although, I aggree, I should document that)

But as I said, I am going to use your work anyway. The only question I have for you now is:

Are you interested to change the pull request in order to achieve the goal I explained?

Please, don't feel obliged. If you are not interested, I'll merge your pull request in a different branch, and improve the feature from there.

Once again, thank you!

**Comment by giovanepadawan** [comment]
Hi, i don't have clear your goal.
The doubt i have is:

> The goal is not to get a failure but to run 100 times.

this assertion goes against the one written in the issue:

> reach the number of iterations (200 by default)

the test case you provided will stop after 10 as it happens right now.

I will not be able to help you anytime soon, feel free to take the changes i made and use them to reach your goal. In case I will have time and the issue will still be open I'll let you know first.

**Comment by jcornaz** [comment]
>this assertion goes against the one written in the issue:
>> reach the number of iterations (200 by default)

Yes, it wasn't clear sorry. I should have phrase it like this:

> reach *at least* the number of iterations (200 by default)

If I rephrased it in the issue to:

> And the property would run for at least the number of iterations (200 by default) and as long as necessary to satisfy at least once the lambda `{ x > 10 }`

Sorry I wasn't clear.

Ok, thanks you very much again, I'll merge in a branch and continue from what you did ;-)

**Pull request merged**
